"""Provides a simple way to test your rules as an external workspace.
Add a basic smoke-test target below.
"""

load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "hello",
    srcs = ["src/main.kt"],
)

build_test(
    name = "smoke_test",
    targets = [
        ":hello",
        "@kmp_deps//:io_ktor_ktor_client_core",
        "@kmp_deps//:io_ktor_ktor_client_core_wasm_js_3_4_3",
        "@kmp_deps//:org_jetbrains_kotlin_kotlin_stdlib",
    ],
)
