bazel_dep(name = "kmp", version = "0.0.0", dev_dependency = True)
bazel_dep(name = "bazel_skylib", version = "1.8.2", dev_dependency = True)

bazel_dep(name = "rules_kotlin", version = "2.3.20")

local_path_override(
    module_name = "kmp",
    path = "../..",
)

kmp_extension = use_extension("@kmp//kmp:extensions.bzl", "kmp")
kmp_extension.configure(
    deps = [
        "io.ktor:ktor-client-cio:3.4.3",
        "io.ktor:ktor-client-core:3.4.3",
    ],
)
use_repo(kmp_extension, "kmp_deps")
